workflows:
  ios-build:
    name: iOS Build (XcodeGen)
    environment:
      xcode: latest
    scripts:
      - name: Install XcodeGen
        script: brew install xcodegen
      - name: Generate Xcode Project
        script: xcodegen generate
      - name: Build iOS app for Device
        script: |
          xcodebuild clean build -project RustRaidAlarm.xcodeproj -scheme RustRaidAlarm -destination 'generic/platform=iOS' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO CONFIGURATION_BUILD_DIR=$PWD/build/Release-iphoneos
      - name: Package into IPA
        script: |
          mkdir -p build/Payload
          cp -R build/Release-iphoneos/RustRaidAlarm.app build/Payload/
          cd build
          zip -qr RustRaidAlarm.ipa Payload
    artifacts:
      - build/RustRaidAlarm.ipa
